dataset:
  name: "food101"
  split: "train"
  batch_size: 64
  num_workers: 0

training:
  num_epochs: 15
  lr: 0.0002            # Более низкий LR для стабильной сходимости
  log_dir: "./logs/sae_training_v2"
  checkpoint_dir: "./checkpoints_v2"
  save_every_epoch: true
  # num_workers: 2